import type {
  AIProvider,
  AdminUser,
  AppSettings,
  AuditLog,
  ChartDataPoint,
  FeatureFlags,
  Notification,
  Plan,
  PromptTemplate,
  SessionRecord,
  Subscription,
  Tool,
  User,
} from "@/types/admin";

const daysAgo = (days: number) =>
  new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

export const adminMockState: {
  adminUsers: AdminUser[];
  users: User[];
  subscriptions: Subscription[];
  plans: Plan[];
  providers: AIProvider[];
  prompts: PromptTemplate[];
  tools: Tool[];
  notifications: Notification[];
  auditLogs: AuditLog[];
  sessions: SessionRecord[];
  appSettings: AppSettings;
  featureFlags: FeatureFlags;
  chartData: {
    registrations: ChartDataPoint[];
    aiUsage: ChartDataPoint[];
    conversions: ChartDataPoint[];
    templateUsage: ChartDataPoint[];
    providerDistribution: ChartDataPoint[];
    userGrowth: ChartDataPoint[];
  };
} = {
  adminUsers: [
    {
      id: "adm_1",
      name: "Maya Chen",
      email: "maya@softkey.ai",
      role: "super_admin",
      avatarUrl: "",
      isActive: true,
      lastLoginAt: daysAgo(0),
      createdAt: daysAgo(280),
    },
    {
      id: "adm_2",
      name: "Jordan Blake",
      email: "jordan@softkey.ai",
      role: "ops",
      avatarUrl: "",
      isActive: true,
      lastLoginAt: daysAgo(1),
      createdAt: daysAgo(180),
    },
  ],
  plans: [
    {
      id: "plan_free",
      name: "Starter",
      slug: "starter",
      description: "Entry access for discovery and lightweight use.",
      priceMonthly: 0,
      priceYearly: 0,
      currency: "USD",
      aiCallQuota: 60,
      modelAccess: ["GPT-4o mini", "Gemini Flash"],
      features: ["Chat", "Templates", "Tools Directory"],
      isActive: true,
      sortOrder: 1,
      activeSubscribers: 1520,
      revenueMonthly: 0,
      revenueYearly: 0,
    },
    {
      id: "plan_pro",
      name: "Pro",
      slug: "pro",
      description: "For creators and daily AI power users.",
      priceMonthly: 19,
      priceYearly: 190,
      currency: "USD",
      aiCallQuota: 2500,
      modelAccess: ["GPT-4o", "Claude Sonnet", "Gemini Pro", "Mistral Large"],
      features: [
        "Priority providers",
        "Prompt library",
        "Usage analytics",
        "Email broadcasts",
      ],
      isActive: true,
      sortOrder: 2,
      activeSubscribers: 620,
      revenueMonthly: 11780,
      revenueYearly: 19000,
    },
    {
      id: "plan_business",
      name: "Business",
      slug: "business",
      description: "Operational controls for teams and agencies.",
      priceMonthly: 49,
      priceYearly: 490,
      currency: "USD",
      aiCallQuota: 10000,
      modelAccess: ["GPT-4.1", "Claude Opus", "Gemini Pro", "Mistral Large"],
      features: ["Team access", "Audit logs", "Feature flags", "Rate limits"],
      isActive: true,
      sortOrder: 3,
      activeSubscribers: 108,
      revenueMonthly: 5292,
      revenueYearly: 4900,
    },
  ],
  subscriptions: [
    {
      id: "sub_1",
      userId: "user_1",
      planId: "plan_pro",
      status: "active",
      cycle: "monthly",
      amount: 19,
      currency: "USD",
      startedAt: daysAgo(28),
      currentPeriodEnd: daysAgo(-2),
      canceledAt: null,
      paymentStatus: "paid",
      provider: "stripe",
      externalSubscriptionId: "sub_9X1",
    },
    {
      id: "sub_2",
      userId: "user_2",
      planId: "plan_business",
      status: "active",
      cycle: "yearly",
      amount: 490,
      currency: "USD",
      startedAt: daysAgo(120),
      currentPeriodEnd: daysAgo(245),
      canceledAt: null,
      paymentStatus: "paid",
      provider: "stripe",
      externalSubscriptionId: "sub_9X2",
    },
    {
      id: "sub_3",
      userId: "user_4",
      planId: "plan_pro",
      status: "past_due",
      cycle: "monthly",
      amount: 19,
      currency: "USD",
      startedAt: daysAgo(18),
      currentPeriodEnd: daysAgo(12),
      canceledAt: null,
      paymentStatus: "pending",
      provider: "stripe",
      externalSubscriptionId: "sub_9X3",
    },
    {
      id: "sub_4",
      userId: "user_6",
      planId: "plan_free",
      status: "trialing",
      cycle: "monthly",
      amount: 0,
      currency: "USD",
      startedAt: daysAgo(3),
      currentPeriodEnd: daysAgo(27),
      canceledAt: null,
      paymentStatus: "pending",
      provider: "stripe",
      externalSubscriptionId: "sub_9X4",
    },
  ],
  users: [
    {
      id: "user_1",
      is_admin:4,
      name: "Ava Johnson",
      email: "ava@example.com",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Ava",
      status: "active",
      planId: "plan_pro",
      aiUsage: 1240,
      joinedAt: daysAgo(120),
      lastActiveAt: daysAgo(0),
      country: "United States",
      source: "Google",
      totalSpent: 76,
      usageMinutes: 420,
      chatCount: 182,
      templateCount: 29,
      toolClicks: 11,
    },
    {
      id: "user_2",
      name: "Noah Patel",
      is_admin:4,
      email: "noah@example.com",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Noah",
      status: "active",
      planId: "plan_business",
      aiUsage: 5800,
      joinedAt: daysAgo(210),
      lastActiveAt: daysAgo(0),
      country: "United Kingdom",
      source: "Organic",
      totalSpent: 490,
      usageMinutes: 1180,
      chatCount: 732,
      templateCount: 84,
      toolClicks: 38,
    },
    {
      id: "user_3",
      is_admin:4,
      name: "Sophia Kim",
      email: "sophia@example.com",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Sophia",
      status: "unverified",
      planId: "plan_free",
      aiUsage: 42,
      joinedAt: daysAgo(2),
      lastActiveAt: daysAgo(2),
      country: "Canada",
      source: "Referral",
      totalSpent: 0,
      usageMinutes: 18,
      chatCount: 7,
      templateCount: 1,
      toolClicks: 2,
    },
    {
      id: "user_4",
      name: "Ethan Ross",
      is_admin:4,
      email: "ethan@example.com",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Ethan",
      status: "active",
      planId: "plan_pro",
      aiUsage: 3310,
      joinedAt: daysAgo(90),
      lastActiveAt: daysAgo(1),
      country: "Australia",
      source: "X",
      totalSpent: 57,
      usageMinutes: 690,
      chatCount: 250,
      templateCount: 42,
      toolClicks: 19,
    },
    {
      id: "user_5",
      name: "Mia Garcia",
      is_admin:4,
      email: "mia@example.com",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Mia",
      status: "suspended",
      planId: "plan_free",
      aiUsage: 85,
      joinedAt: daysAgo(45),
      lastActiveAt: daysAgo(15),
      country: "Spain",
      source: "Organic",
      totalSpent: 0,
      usageMinutes: 22,
      chatCount: 15,
      templateCount: 4,
      toolClicks: 5,
    },
    {
      id: "user_6",
      name: "Oliver Brown",
      email: "oliver@example.com",
      is_admin:4,
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Oliver",
      status: "active",
      planId: "plan_free",
      aiUsage: 220,
      joinedAt: daysAgo(8),
      lastActiveAt: daysAgo(0),
      country: "Singapore",
      source: "Landing Page",
      totalSpent: 0,
      usageMinutes: 60,
      chatCount: 29,
      templateCount: 10,
      toolClicks: 7,
    },
    {
      id: "user_7",
      name: "Isabella Silva",
      is_admin:4,
      email: "isabella@example.com",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Isabella",
      status: "active",
      planId: "plan_business",
      aiUsage: 9200,
      joinedAt: daysAgo(310),
      lastActiveAt: daysAgo(1),
      country: "Brazil",
      source: "LinkedIn",
      totalSpent: 490,
      usageMinutes: 1560,
      chatCount: 1034,
      templateCount: 121,
      toolClicks: 55,
    },
    {
      id: "user_8",
      name: "Lucas Nguyen",
      email: "lucas@example.com",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Lucas",
      status: "active",
      is_admin:4,
      planId: "plan_pro",
      aiUsage: 2180,
      joinedAt: daysAgo(65),
      lastActiveAt: daysAgo(2),
      country: "Vietnam",
      source: "Organic",
      totalSpent: 38,
      usageMinutes: 480,
      chatCount: 160,
      templateCount: 23,
      toolClicks: 14,
    },
    {
      id: "user_9",
      name: "Zara Khan",
      email: "zara@example.com",
      is_admin:4,
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Zara",
      status: "unverified",
      planId: "plan_free",
      aiUsage: 12,
      joinedAt: daysAgo(1),
      lastActiveAt: daysAgo(1),
      country: "Pakistan",
      source: "Twitter",
      totalSpent: 0,
      usageMinutes: 4,
      chatCount: 3,
      templateCount: 0,
      toolClicks: 1,
    },
    {
      id: "user_10",
      name: "James Walker",
      email: "james@example.com",
      is_admin:4,
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=James",
      status: "active",
      planId: "plan_pro",
      aiUsage: 1760,
      joinedAt: daysAgo(33),
      lastActiveAt: daysAgo(0),
      country: "United States",
      source: "Referral",
      totalSpent: 19,
      usageMinutes: 360,
      chatCount: 98,
      templateCount: 21,
      toolClicks: 16,
    },
    {
      id: "user_11",
      name: "Hana Sato",
      is_admin:4,
      email: "hana@example.com",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Hana",
      status: "active",
      planId: "plan_free",
      aiUsage: 180,
      joinedAt: daysAgo(18),
      lastActiveAt: daysAgo(3),
      country: "Japan",
      source: "Organic",
      totalSpent: 0,
      usageMinutes: 45,
      chatCount: 24,
      templateCount: 8,
      toolClicks: 6,
    },
    {
      id: "user_12",
      name: "Daniel Green",
      email: "daniel@example.com",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Daniel",
      status: "suspended",
      planId: "plan_business",
      is_admin:4,
      aiUsage: 6400,
      joinedAt: daysAgo(260),
      lastActiveAt: daysAgo(42),
      country: "Germany",
      source: "Google",
      totalSpent: 490,
      usageMinutes: 890,
      chatCount: 420,
      templateCount: 56,
      toolClicks: 26,
    },
  ],
  providers: [
    {
      id: "openai",
      name: "OpenAI",
      slug: "openai",
      isEnabled: true,
      status: "active",
      priority: 1,
      maskedApiKey: "sk-••••••••••••••••A1",
      models: ["GPT-4.1", "GPT-4o", "GPT-4o mini"],
      fallbackOrder: ["openai", "claude", "gemini", "mistral"],
      usage: {
        providerId: "openai",
        providerName: "OpenAI",
        monthlyUsage: 224000,
        monthlyLimit: 300000,
        errorRate: 0.8,
        averageLatencyMs: 840,
        lastCheckedAt: daysAgo(0),
      },
      monthlyUsage: 224000,
      monthlyLimit: 300000,
      healthMessage: "Healthy, low latency",
      lastCheckedAt: daysAgo(0),
    },
    {
      id: "gemini",
      name: "Gemini",
      slug: "gemini",
      isEnabled: true,
      status: "active",
      priority: 2,
      maskedApiKey: "AIza••••••••••••b2",
      models: ["Gemini 2.0 Flash", "Gemini 2.0 Pro"],
      fallbackOrder: ["openai", "claude", "gemini", "mistral"],
      usage: {
        providerId: "gemini",
        providerName: "Gemini",
        monthlyUsage: 154000,
        monthlyLimit: 220000,
        errorRate: 1.2,
        averageLatencyMs: 910,
        lastCheckedAt: daysAgo(0),
      },
      monthlyUsage: 154000,
      monthlyLimit: 220000,
      healthMessage: "Healthy",
      lastCheckedAt: daysAgo(0),
    },
    {
      id: "claude",
      name: "Claude",
      slug: "claude",
      isEnabled: true,
      status: "active",
      priority: 3,
      maskedApiKey: "sk-ant-••••••••••c3",
      models: ["Claude Sonnet 4", "Claude Opus 4"],
      fallbackOrder: ["openai", "claude", "gemini", "mistral"],
      usage: {
        providerId: "claude",
        providerName: "Claude",
        monthlyUsage: 86000,
        monthlyLimit: 140000,
        errorRate: 0.5,
        averageLatencyMs: 960,
        lastCheckedAt: daysAgo(0),
      },
      monthlyUsage: 86000,
      monthlyLimit: 140000,
      healthMessage: "Healthy",
      lastCheckedAt: daysAgo(0),
    },
    {
      id: "mistral",
      name: "Mistral",
      slug: "mistral",
      isEnabled: false,
      status: "disabled",
      priority: 4,
      maskedApiKey: "sk-••••••••••••••••d4",
      models: ["Mistral Large", "Mistral Small"],
      fallbackOrder: ["openai", "claude", "gemini", "mistral"],
      usage: {
        providerId: "mistral",
        providerName: "Mistral",
        monthlyUsage: 21000,
        monthlyLimit: 90000,
        errorRate: 2.8,
        averageLatencyMs: 1100,
        lastCheckedAt: daysAgo(1),
      },
      monthlyUsage: 21000,
      monthlyLimit: 90000,
      healthMessage: "Disabled by admin",
      lastCheckedAt: daysAgo(1),
    },
  ],
  prompts: [
    {
      id: "prompt_1",
      name: "Landing Page Hero Copy",
      slug: "landing-page-hero-copy",
      category: "Marketing",
      author: "Maya Chen",
      description: "",
      content: "Write a conversion-focused hero section for an AI product.",
      tags: ["marketing", "hero", "copy"],
      usageCount: 2310,
      isFeatured: true,
      isPublished: true,
      status: "published",
      createdAt: daysAgo(42),
      updatedAt: daysAgo(0),
    },
    {
      id: "prompt_2",
      name: "Support Reply Draft",
      slug: "support-reply-draft",
      category: "Support",
      author: "Jordan Blake",
      description: "",
      content: "Draft a concise support response with empathy and a solution.",
      tags: ["support", "email"],
      usageCount: 1801,
      isFeatured: false,
      isPublished: true,
      status: "published",
      createdAt: daysAgo(38),
      updatedAt: daysAgo(1),
    },
    {
      id: "prompt_3",
      name: "YouTube Script Outline",
      slug: "youtube-script-outline",
      category: "Content",
      author: "Maya Chen",
      description: "",
      content: "Create a YouTube video outline with hook, body, and CTA.",
      tags: ["youtube", "content"],
      usageCount: 1544,
      isFeatured: true,
      isPublished: true,
      status: "published",
      createdAt: daysAgo(28),
      updatedAt: daysAgo(2),
    },
    {
      id: "prompt_4",
      name: "SEO Blog Brief",
      slug: "seo-blog-brief",
      category: "SEO",
      author: "Jordan Blake",
      description: "",
      content: "Generate an SEO blog brief with headings and target keywords.",
      tags: ["seo", "blog"],
      usageCount: 990,
      isFeatured: false,
      isPublished: true,
      status: "published",
      createdAt: daysAgo(24),
      updatedAt: daysAgo(3),
    },
    {
      id: "prompt_5",
      name: "Product Hunt Launch Post",
      slug: "product-hunt-launch-post",
      category: "Marketing",
      author: "Maya Chen",
      description: "",
      content: "Write a Product Hunt launch post for a SaaS launch.",
      tags: ["launch", "ph"],
      usageCount: 815,
      isFeatured: true,
      isPublished: false,
      status: "draft",
      createdAt: daysAgo(17),
      updatedAt: daysAgo(4),
    },
    {
      id: "prompt_6",
      name: "Feature Comparison Table",
      slug: "feature-comparison-table",
      category: "Sales",
      author: "Jordan Blake",
      description: "",
      content: "Compare two products in a clear feature table.",
      tags: ["sales", "comparison"],
      usageCount: 701,
      isFeatured: false,
      isPublished: true,
      status: "published",
      createdAt: daysAgo(13),
      updatedAt: daysAgo(0),
    },
    {
      id: "prompt_7",
      name: "Cold Email Sequence",
      slug: "cold-email-sequence",
      category: "Outbound",
      author: "Maya Chen",
      description: "",
      content: "Build a 3-step cold email sequence for B2B outreach.",
      tags: ["email", "outbound"],
      usageCount: 520,
      isFeatured: false,
      isPublished: true,
      status: "published",
      createdAt: daysAgo(12),
      updatedAt: daysAgo(5),
    },
    {
      id: "prompt_8",
      name: "UX Research Summary",
      slug: "ux-research-summary",
      category: "Product",
      author: "Jordan Blake",
      description: "",
      content: "Summarize research notes into actionable product insights.",
      tags: ["ux", "research"],
      usageCount: 430,
      isFeatured: false,
      isPublished: false,
      status: "draft",
      createdAt: daysAgo(8),
      updatedAt: daysAgo(1),
    },
  ],
  tools: [
    {
      id: "tool_1",
      name: "AI Image Studio",
      slug: "ai-image-studio",
      category: "Image",
      description: "Generate and edit marketing-ready visuals.",
      url: "https://example.com/image",
      logoUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=ImageStudio",
      tags: ["image", "editing"],
      isFeatured: true,
      status: "active",
      clickCount: 8100,
      createdAt: daysAgo(80),
      updatedAt: daysAgo(0),
    },
    {
      id: "tool_2",
      name: "Chat Copilot",
      slug: "chat-copilot",
      category: "Chat",
      description: "Quick-start assistant for customer support teams.",
      url: "https://example.com/chat",
      logoUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=ChatCopilot",
      tags: ["chat", "support"],
      isFeatured: true,
      status: "active",
      clickCount: 6940,
      createdAt: daysAgo(72),
      updatedAt: daysAgo(0),
    },
    {
      id: "tool_3",
      name: "Prompt Forge",
      slug: "prompt-forge",
      category: "Prompts",
      description: "Build and test high-performing prompts.",
      url: "https://example.com/prompt",
      logoUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=PromptForge",
      tags: ["prompt", "library"],
      isFeatured: false,
      status: "active",
      clickCount: 5120,
      createdAt: daysAgo(62),
      updatedAt: daysAgo(2),
    },
    {
      id: "tool_4",
      name: "SEO Radar",
      slug: "seo-radar",
      category: "SEO",
      description: "Audit content and search intent quickly.",
      url: "https://example.com/seo",
      logoUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=SEORadar",
      tags: ["seo", "audit"],
      isFeatured: false,
      status: "draft",
      clickCount: 3210,
      createdAt: daysAgo(54),
      updatedAt: daysAgo(4),
    },
    {
      id: "tool_5",
      name: "LaunchBoard",
      slug: "launchboard",
      category: "Marketing",
      description: "Campaign planner for product launches.",
      url: "https://example.com/launch",
      logoUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=LaunchBoard",
      tags: ["launch", "marketing"],
      isFeatured: true,
      status: "active",
      clickCount: 4480,
      createdAt: daysAgo(41),
      updatedAt: daysAgo(0),
    },
    {
      id: "tool_6",
      name: "Analytics Lens",
      slug: "analytics-lens",
      category: "Analytics",
      description: "Interpret product and revenue signals.",
      url: "https://example.com/analytics",
      logoUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=AnalyticsLens",
      tags: ["analytics", "revenue"],
      isFeatured: false,
      status: "archived",
      clickCount: 1900,
      createdAt: daysAgo(33),
      updatedAt: daysAgo(7),
    },
  ],
  notifications: [
    {
      id: "note_1",
      type: "announcement",
      title: "New Claude routing live",
      body: "Claude is now enabled as a primary fallback for Pro and Business plans.",
      audience: "All users",
      status: "sent",
      scheduleAt: null,
      createdAt: daysAgo(1),
    },
    {
      id: "note_2",
      type: "in_app",
      title: "Maintenance notice",
      body: "A short maintenance window is planned for tonight.",
      audience: "Logged-in users",
      status: "scheduled",
      scheduleAt: daysAgo(-1),
      createdAt: daysAgo(0),
    },
    {
      id: "note_3",
      type: "email",
      title: "Upgrade reminder",
      body: "Trial users receive a plan upgrade reminder at 80% usage.",
      audience: "Trial users",
      status: "draft",
      scheduleAt: null,
      createdAt: daysAgo(4),
    },
  ],
  auditLogs: [
    {
      id: "log_1",
      actor: "Maya Chen",
      action: "Updated plan pricing",
      entity: "Plan",
      entityId: "plan_pro",
      summary: "Pro plan monthly pricing changed to $19.",
      ipAddress: "10.0.0.12",
      severity: "info",
      createdAt: daysAgo(0),
    },
    {
      id: "log_2",
      actor: "Jordan Blake",
      action: "Disabled provider",
      entity: "AI Provider",
      entityId: "mistral",
      summary: "Mistral marked disabled after quota review.",
      ipAddress: "10.0.0.19",
      severity: "warning",
      createdAt: daysAgo(1),
    },
    {
      id: "log_3",
      actor: "Maya Chen",
      action: "Suspended user",
      entity: "User",
      entityId: "user_5",
      summary: "User suspended for suspicious billing activity.",
      ipAddress: "10.0.0.12",
      severity: "critical",
      createdAt: daysAgo(2),
    },
    {
      id: "log_4",
      actor: "Jordan Blake",
      action: "Published prompt",
      entity: "Prompt",
      entityId: "prompt_4",
      summary: "SEO Blog Brief published to the library.",
      ipAddress: "10.0.0.19",
      severity: "info",
      createdAt: daysAgo(2),
    },
    {
      id: "log_5",
      actor: "Maya Chen",
      action: "Toggled maintenance",
      entity: "Settings",
      entityId: "maintenance",
      summary: "Maintenance mode switched off after deployment.",
      ipAddress: "10.0.0.12",
      severity: "warning",
      createdAt: daysAgo(3),
    },
  ],
  sessions: [
    {
      id: "sess_1",
      userId: "user_1",
      device: "MacBook Pro",
      browser: "Chrome",
      ipAddress: "172.16.4.11",
      location: "New York, US",
      status: "active",
      createdAt: daysAgo(1),
      lastSeenAt: daysAgo(0),
    },
    {
      id: "sess_2",
      userId: "user_1",
      device: "iPhone 15",
      browser: "Safari",
      ipAddress: "172.16.4.15",
      location: "New York, US",
      status: "expired",
      createdAt: daysAgo(14),
      lastSeenAt: daysAgo(12),
    },
    {
      id: "sess_3",
      userId: "user_2",
      device: "Windows Desktop",
      browser: "Edge",
      ipAddress: "172.16.9.23",
      location: "London, UK",
      status: "active",
      createdAt: daysAgo(3),
      lastSeenAt: daysAgo(0),
    },
    {
      id: "sess_4",
      userId: "user_4",
      device: "Pixel 8",
      browser: "Chrome",
      ipAddress: "172.16.8.53",
      location: "Sydney, AU",
      status: "revoked",
      createdAt: daysAgo(20),
      lastSeenAt: daysAgo(18),
    },
    {
      id: "sess_5",
      userId: "user_7",
      device: "Mac Studio",
      browser: "Firefox",
      ipAddress: "172.16.6.77",
      location: "Sao Paulo, BR",
      status: "active",
      createdAt: daysAgo(5),
      lastSeenAt: daysAgo(0),
    },
  ],
  appSettings: {
    siteName: "Softkey AI",
    supportEmail: "support@softkey.ai",
    contactUrl: "https://softkey.ai/contact",
    maintenanceMode: false,
    maintenanceMessage: "We are currently performing scheduled maintenance.",
    logoUrl: "",
    primaryColor: "#4f46e5",
    brandTagline: "Multi-model AI operations for serious teams.",
    emailFromName: "Softkey AI",
    emailFromAddress: "noreply@softkey.ai",
  },
  featureFlags: {
    new_chat: true,
    tools_dir: true,
    prompt_library: true,
    referral_program: false,
  },
  chartData: {
    registrations: [
      { label: "Mon", value: 28 },
      { label: "Tue", value: 34 },
      { label: "Wed", value: 29 },
      { label: "Thu", value: 41 },
      { label: "Fri", value: 48 },
      { label: "Sat", value: 39 },
      { label: "Sun", value: 53 },
    ],
    aiUsage: [
      { label: "Mon", value: 12100 },
      { label: "Tue", value: 13600 },
      { label: "Wed", value: 13300 },
      { label: "Thu", value: 14500 },
      { label: "Fri", value: 15700 },
      { label: "Sat", value: 14900 },
      { label: "Sun", value: 16800 },
    ],
    conversions: [
      { label: "Free", value: 5400 },
      { label: "Trial", value: 1840 },
      { label: "Paid", value: 728 },
    ],
    templateUsage: [
      { label: "Hero Copy", value: 2310 },
      { label: "Support Reply", value: 1801 },
      { label: "YouTube Outline", value: 1544 },
      { label: "SEO Brief", value: 990 },
      { label: "Launch Post", value: 815 },
    ],
    providerDistribution: [
      { label: "OpenAI", value: 51, color: "#4f46e5" },
      { label: "Gemini", value: 24, color: "#10b981" },
      { label: "Claude", value: 17, color: "#f59e0b" },
      { label: "Mistral", value: 8, color: "#ef4444" },
    ],
    userGrowth: [
      { label: "Jan", value: 840 },
      { label: "Feb", value: 980 },
      { label: "Mar", value: 1170 },
      { label: "Apr", value: 1360 },
      { label: "May", value: 1490 },
      { label: "Jun", value: 1630 },
      { label: "Jul", value: 1820 },
      { label: "Aug", value: 2010 },
      { label: "Sep", value: 2240 },
      { label: "Oct", value: 2510 },
      { label: "Nov", value: 2820 },
      { label: "Dec", value: 3140 },
    ],
  },
};
